#include "struct.h"
#include "prtInfo.h"
#include <ncurses.h>
void prt( int32_t index, char * str , int32_t o){
	if( !index ){
		printw("%s",str);
		return;
	}
	init_pair(1, COLOR_RED, COLOR_BLACK);
	init_pair(2, COLOR_GREEN, COLOR_BLACK);
	init_pair(3, COLOR_YELLOW, COLOR_BLACK);
	init_pair(4, COLOR_BLUE, COLOR_BLACK);
	attron(COLOR_PAIR(o) | A_BLINK);
    printw("%s",str);
    attroff(COLOR_PAIR(o) | A_BLINK);
}
void prtNode( Player * player, road * proad, node * pnode ,int32_t build_index[54] ){
	//int32_t build_index[54] = {0};
	//TODO:change index to 1 if buyable
    initscr();
	start_color();
    printw("                 ");
	prt(build_index[0],"01",player->index);
	printw("---");
	prt(build_index[1],"02",player->index);
	printw("\n");
	//--- 1
    printw("                 /     \\\n");
    printw("           ");
	prt(build_index[2],"03",player->index);
	printw("---");
	prt(build_index[3],"04",player->index);
	printw("     ");
	prt(build_index[4],"05",player->index);
	printw("---");
	prt(build_index[5],"06",player->index);
	printw("\n");
    printw("           /     \\     /     \\\n");
    printw("     ");
	prt(build_index[6],"07",player->index);
	printw("---");
	prt(build_index[7],"08",player->index);
	printw("     ");
	prt(build_index[8],"09",player->index);
	printw("---");
	prt(build_index[9],"10",player->index);
	printw("     ");
	prt(build_index[10],"11",player->index);
	printw("---");
	prt(build_index[11],"12",player->index);
	printw("\n");
	//---2
    printw("     /     \\     /     \\     /     \\\n");
    printw("   ");
	prt(build_index[12],"13",player->index);
	printw("      ");
	prt(build_index[13],"14",player->index);
	printw("---");
	prt(build_index[14],"15",player->index);
	printw("     ");
	prt(build_index[15],"16",player->index);
	printw("---");
	prt(build_index[16],"17",player->index);
	printw("      ");
	prt(build_index[17],"18",player->index);
	printw("\n");
    printw("     \\     /     \\     /     \\     /\n");
    printw("     ");
	prt(build_index[18],"19",player->index);
	printw("---");
	prt(build_index[19],"20",player->index);
	printw("     ");
	prt(build_index[20],"21",player->index);
	printw("---");
	prt(build_index[21],"22",player->index);
	printw("     ");
	prt(build_index[22],"23",player->index);
	printw("---");
	prt(build_index[23],"24",player->index);
	printw("\n");
    printw("     /     \\     /     \\     /     \\\n");
    printw("   ");
	prt(build_index[24],"25",player->index);
	printw("      ");
	prt(build_index[25],"26",player->index);
	printw("---");
	prt(build_index[26],"27",player->index);
	printw("     ");
	prt(build_index[27],"28",player->index);
	printw("---");
	prt(build_index[28],"29",player->index);
	printw("      ");
	prt(build_index[29],"30",player->index);
	printw("\n");
    printw("     \\     /     \\     /     \\     /\n");
    printw("     ");
	prt(build_index[30],"31",player->index);
	printw("---");
	prt(build_index[31],"32",player->index);
	printw("     ");
	prt(build_index[32],"33",player->index);
	printw("---");
	prt(build_index[33],"34",player->index);
	printw("     ");
	prt(build_index[34],"35",player->index);
	printw("---");
	prt(build_index[35],"36",player->index);
	printw("\n");
    printw("     /     \\     /     \\     /     \\\n");
    printw("   ");
	prt(build_index[36],"37",player->index);
	printw("      ");
	prt(build_index[37],"38",player->index);
	printw("---");
	prt(build_index[38],"39",player->index);
	printw("     ");
	prt(build_index[39],"40",player->index);
	printw("---");
	prt(build_index[40],"41",player->index);
	printw("      ");
	prt(build_index[41],"42",player->index);
	printw("\n");
    printw("     \\     /     \\     /     \\     /\n");
    printw("     ");
	prt(build_index[42],"43",player->index);
	printw("---");
	prt(build_index[43],"44",player->index);
	printw("     ");
	prt(build_index[44],"45",player->index);
	printw("---");
	prt(build_index[45],"46",player->index);
	printw("     ");
	prt(build_index[46],"47",player->index);
	printw("---");
	prt(build_index[47],"48",player->index);
	printw("\n");
    printw("           \\     /     \\     /\n");
    printw("           ");
	prt(build_index[48],"49",player->index);
	printw("---");
	prt(build_index[49],"50",player->index);
	printw("     ");
	prt(build_index[50],"51",player->index);
	printw("---");
	prt(build_index[51],"52",player->index);
	printw("\n");
    printw("                 \\     /\n");
    printw("                 ");
	prt(build_index[52],"53",player->index);
	printw("---");
	prt(build_index[53],"54",player->index);
	printw("\n\n");

    printw("        Press any button to quit!\n");

    refresh();
    // Wait for user input
    getch();
    endwin();
	clear();
}
void prtRoad( Player * player, road * proad, int32_t road_index[54] ){
	//int32_t road_index[72] = {0};
	//TODO:index[i] turn to 1 if buyable
    initscr();

    printw("                  * ");
	prt(road_index[0],"01",player->index);
	printw("*\n");
    printw("                 ");
	prt(road_index[1],"02",player->index);
	printw("    ");
	prt(road_index[2],"03",player->index);
	printw("\n");
    printw("            * ");
	prt(road_index[3],"04",player->index);
	printw("*       * ");
	prt(road_index[4],"05",player->index);
	printw("*\n");
    printw("           ");
	prt(road_index[5],"06",player->index);
	printw("    ");
	prt(road_index[6],"07",player->index);
	printw("    ");
	prt(road_index[7],"08",player->index);
	printw("    ");
	prt(road_index[8],"09",player->index);
	printw("\n");
    printw("      * ");
	prt(road_index[9],"10",player->index);
	printw("*       * ");
	prt(road_index[10],"11",player->index);
	printw("*       * ");
	prt(road_index[11],"12",player->index);
	printw("*\n");
    printw("     ");
	prt(road_index[12],"13",player->index);
	printw("    ");
	prt(road_index[13],"14",player->index);
	printw("    ");
	prt(road_index[14],"15",player->index);
	printw("    ");
	prt(road_index[15],"16",player->index);
	printw("    ");
	prt(road_index[16],"17",player->index);
	printw("    ");
	prt(road_index[17],"18",player->index);
	printw("\n");
    printw("    *       * ");
	prt(road_index[18],"19",player->index);
	printw("*       * ");
	prt(road_index[19],"20",player->index);
	printw("*       *\n");
    printw("     ");
	prt(road_index[20],"21",player->index);
	printw("    ");
	prt(road_index[21],"22",player->index);
	printw("    ");
	prt(road_index[22],"23",player->index);
	printw("    ");
	prt(road_index[23],"24",player->index);
	printw("    ");
	prt(road_index[24],"25",player->index);
	printw("    ");
	prt(road_index[25],"26",player->index);
	printw("\n");
    printw("      * ");
	prt(road_index[26],"27",player->index);
	printw("*       * ");
	prt(road_index[27],"28",player->index);
	printw("*       * ");
	prt(road_index[28],"29",player->index);
	printw("*\n");
    printw("     ");
	prt(road_index[29],"30",player->index);
	printw("    ");
	prt(road_index[30],"31",player->index);
	printw("    ");
	prt(road_index[31],"32",player->index);
	printw("    ");
	prt(road_index[32],"33",player->index);
	printw("    ");
	prt(road_index[33],"34",player->index);
	printw("    ");
	prt(road_index[34],"35",player->index);
	printw("\n");
    printw("    *       * ");
	prt(road_index[35],"36",player->index);
	printw("*       * ");
	prt(road_index[36],"37",player->index);
	printw("*       *\n");
    printw("     ");
	prt(road_index[37],"38",player->index);
	printw("    ");
	prt(road_index[38],"39",player->index);
	printw("    ");
	prt(road_index[39],"40",player->index);
	printw("    ");
	prt(road_index[40],"41",player->index);
	printw("    ");
	prt(road_index[41],"42",player->index);
	printw("    ");
	prt(road_index[42],"43",player->index);
	printw("\n");
    printw("      * ");
	prt(road_index[43],"44",player->index);
	printw("*       * ");
	prt(road_index[44],"45",player->index);
	printw("*       * ");
	prt(road_index[45],"46",player->index);
	printw("*\n");
    printw("     ");
	prt(road_index[46],"47",player->index);
	printw("    ");
	prt(road_index[47],"48",player->index);
	printw("    ");
	prt(road_index[48],"49",player->index);
	printw("    ");
	prt(road_index[49],"50",player->index);
	printw("    ");
	prt(road_index[50],"51",player->index);
	printw("    ");
	prt(road_index[51],"52",player->index);
	printw("\n");
    printw("    *       * ");
	prt(road_index[52],"53",player->index);
	printw("*       * ");
	prt(road_index[53],"54",player->index);
	printw("*       *\n");
    printw("     ");
	prt(road_index[54],"55",player->index);
	printw("    ");
	prt(road_index[55],"56",player->index);
	printw("    ");
	prt(road_index[65],"57",player->index);
	printw("    ");
	prt(road_index[57],"58",player->index);
	printw("    ");
	prt(road_index[58],"59",player->index);
	printw("    ");
	prt(road_index[59],"60",player->index);
	printw("\n");
    printw("      * ");
	prt(road_index[60],"61",player->index);
	printw("*       * ");
	prt(road_index[61],"62",player->index);
	printw("*       * ");
	prt(road_index[62],"63",player->index);
	printw("*\n");
    printw("           ");
	prt(road_index[63],"64",player->index);
	printw("    ");
	prt(road_index[64],"65",player->index);
	printw("    ");
	prt(road_index[65],"66",player->index);
	printw("    ");
	prt(road_index[66],"67",player->index);
	printw("\n");
    printw("            * ");
	prt(road_index[67],"68",player->index);
	printw("*       * ");
	prt(road_index[68],"69",player->index);
	printw("*\n");
    printw("                 ");
	prt(road_index[69],"70",player->index);
	printw("    ");
	prt(road_index[70],"71",player->index);printw("\n");
    printw("                  * ");
	prt(road_index[71],"72",player->index);
	printw("*\n\n");

    printw("        Press any button to quit!\n");
    refresh();

    // Wait for user input
    getch();

    endwin();
	clear();
}
