#include "struct.h"
#include "prtInfo.h"
//#include <ncurses.h>
#include "color.h"
void prt( int32_t index, char * str , int32_t owner){
	if( !index ){
		printf("%s",str);
		return;
	}
	if( owner == 1 ) printf( CLR_LRED );
    else if( owner == 2 ) printf( CLR_LGRN );
    else if( owner == 3 ) printf( CLR_LYLW );
    else if( owner == 4 ) printf( CLR_CYN );
    else printf( CLR_RST );
	//init_pair(1, COLOR_RED, COLOR_BLACK);
	//init_pair(2, COLOR_GREEN, COLOR_BLACK);
	//init_pair(3, COLOR_YELLOW, COLOR_BLACK);
	//init_pair(4, COLOR_BLUE, COLOR_BLACK);
	//attron(COLOR_PAIR(o) | A_BLINK);
    printf("\033[5m%s"CLR_RST,str);
    //attroff(COLOR_PAIR(o) | A_BLINK);
}
void prtNode( Player * player, road * proad, node * pnode ,int32_t build_index[54] ){
	//int32_t build_index[54] = {0};
	//TODO:change index to 1 if buyable
    //initscr();
	//start_color();
    printf("\033[2J\033[H");	
    printf("                 ");
	prt(build_index[0],"01",player->index);
	printf("---");
	prt(build_index[1],"02",player->index);
	printf("\n");
	//--- 1
    printf("                 /     \\\n");
    printf("           ");
	prt(build_index[2],"03",player->index);
	printf("---");
	prt(build_index[3],"04",player->index);
	printf("     ");
	prt(build_index[4],"05",player->index);
	printf("---");
	prt(build_index[5],"06",player->index);
	printf("\n");
    printf("           /     \\     /     \\\n");
    printf("     ");
	prt(build_index[6],"07",player->index);
	printf("---");
	prt(build_index[7],"08",player->index);
	printf("     ");
	prt(build_index[8],"09",player->index);
	printf("---");
	prt(build_index[9],"10",player->index);
	printf("     ");
	prt(build_index[10],"11",player->index);
	printf("---");
	prt(build_index[11],"12",player->index);
	printf("\n");
	//---2
    printf("     /     \\     /     \\     /     \\\n");
    printf("   ");
	prt(build_index[12],"13",player->index);
	printf("      ");
	prt(build_index[13],"14",player->index);
	printf("---");
	prt(build_index[14],"15",player->index);
	printf("     ");
	prt(build_index[15],"16",player->index);
	printf("---");
	prt(build_index[16],"17",player->index);
	printf("      ");
	prt(build_index[17],"18",player->index);
	printf("\n");
    printf("     \\     /     \\     /     \\     /\n");
    printf("     ");
	prt(build_index[18],"19",player->index);
	printf("---");
	prt(build_index[19],"20",player->index);
	printf("     ");
	prt(build_index[20],"21",player->index);
	printf("---");
	prt(build_index[21],"22",player->index);
	printf("     ");
	prt(build_index[22],"23",player->index);
	printf("---");
	prt(build_index[23],"24",player->index);
	printf("\n");
    printf("     /     \\     /     \\     /     \\\n");
    printf("   ");
	prt(build_index[24],"25",player->index);
	printf("      ");
	prt(build_index[25],"26",player->index);
	printf("---");
	prt(build_index[26],"27",player->index);
	printf("     ");
	prt(build_index[27],"28",player->index);
	printf("---");
	prt(build_index[28],"29",player->index);
	printf("      ");
	prt(build_index[29],"30",player->index);
	printf("\n");
    printf("     \\     /     \\     /     \\     /\n");
    printf("     ");
	prt(build_index[30],"31",player->index);
	printf("---");
	prt(build_index[31],"32",player->index);
	printf("     ");
	prt(build_index[32],"33",player->index);
	printf("---");
	prt(build_index[33],"34",player->index);
	printf("     ");
	prt(build_index[34],"35",player->index);
	printf("---");
	prt(build_index[35],"36",player->index);
	printf("\n");
    printf("     /     \\     /     \\     /     \\\n");
    printf("   ");
	prt(build_index[36],"37",player->index);
	printf("      ");
	prt(build_index[37],"38",player->index);
	printf("---");
	prt(build_index[38],"39",player->index);
	printf("     ");
	prt(build_index[39],"40",player->index);
	printf("---");
	prt(build_index[40],"41",player->index);
	printf("      ");
	prt(build_index[41],"42",player->index);
	printf("\n");
    printf("     \\     /     \\     /     \\     /\n");
    printf("     ");
	prt(build_index[42],"43",player->index);
	printf("---");
	prt(build_index[43],"44",player->index);
	printf("     ");
	prt(build_index[44],"45",player->index);
	printf("---");
	prt(build_index[45],"46",player->index);
	printf("     ");
	prt(build_index[46],"47",player->index);
	printf("---");
	prt(build_index[47],"48",player->index);
	printf("\n");
    printf("           \\     /     \\     /\n");
    printf("           ");
	prt(build_index[48],"49",player->index);
	printf("---");
	prt(build_index[49],"50",player->index);
	printf("     ");
	prt(build_index[50],"51",player->index);
	printf("---");
	prt(build_index[51],"52",player->index);
	printf("\n");
    printf("                 \\     /\n");
    printf("                 ");
	prt(build_index[52],"53",player->index);
	printf("---");
	prt(build_index[53],"54",player->index);
	printf("\n\n");

    //printw("        Press any button to quit!\n");

    /*refresh();
    // Wait for user input
    getch();
	clear();
    endwin();*/
	
}
void prtRoad( Player * player, road * proad, int32_t road_index[72] ){
	//int32_t road_index[72] = {0};
	//TODO:index[i] turn to 1 if buyable
    //initscr();
    printf("\033[2J\033[H");
    printf("                  * ");
	prt(road_index[0],"01",player->index);
	printf("*\n");
    printf("                 ");
	prt(road_index[1],"02",player->index);
	printf("    ");
	prt(road_index[2],"03",player->index);
	printf("\n");
    printf("            * ");
	prt(road_index[3],"04",player->index);
	printf("*       * ");
	prt(road_index[4],"05",player->index);
	printf("*\n");
    printf("           ");
	prt(road_index[5],"06",player->index);
	printf("    ");
	prt(road_index[6],"07",player->index);
	printf("    ");
	prt(road_index[7],"08",player->index);
	printf("    ");
	prt(road_index[8],"09",player->index);
	printf("\n");
    printf("      * ");
	prt(road_index[9],"10",player->index);
	printf("*       * ");
	prt(road_index[10],"11",player->index);
	printf("*       * ");
	prt(road_index[11],"12",player->index);
	printf("*\n");
    printf("     ");
	prt(road_index[12],"13",player->index);
	printf("    ");
	prt(road_index[13],"14",player->index);
	printf("    ");
	prt(road_index[14],"15",player->index);
	printf("    ");
	prt(road_index[15],"16",player->index);
	printf("    ");
	prt(road_index[16],"17",player->index);
	printf("    ");
	prt(road_index[17],"18",player->index);
	printf("\n");
    printf("    *       * ");
	prt(road_index[18],"19",player->index);
	printf("*       * ");
	prt(road_index[19],"20",player->index);
	printf("*       *\n");
    printf("     ");
	prt(road_index[20],"21",player->index);
	printf("    ");
	prt(road_index[21],"22",player->index);
	printf("    ");
	prt(road_index[22],"23",player->index);
	printf("    ");
	prt(road_index[23],"24",player->index);
	printf("    ");
	prt(road_index[24],"25",player->index);
	printf("    ");
	prt(road_index[25],"26",player->index);
	printf("\n");
    printf("      * ");
	prt(road_index[26],"27",player->index);
	printf("*       * ");
	prt(road_index[27],"28",player->index);
	printf("*       * ");
	prt(road_index[28],"29",player->index);
	printf("*\n");
    printf("     ");
	prt(road_index[29],"30",player->index);
	printf("    ");
	prt(road_index[30],"31",player->index);
	printf("    ");
	prt(road_index[31],"32",player->index);
	printf("    ");
	prt(road_index[32],"33",player->index);
	printf("    ");
	prt(road_index[33],"34",player->index);
	printf("    ");
	prt(road_index[34],"35",player->index);
	printf("\n");
    printf("    *       * ");
	prt(road_index[35],"36",player->index);
	printf("*       * ");
	prt(road_index[36],"37",player->index);
	printf("*       *\n");
    printf("     ");
	prt(road_index[37],"38",player->index);
	printf("    ");
	prt(road_index[38],"39",player->index);
	printf("    ");
	prt(road_index[39],"40",player->index);
	printf("    ");
	prt(road_index[40],"41",player->index);
	printf("    ");
	prt(road_index[41],"42",player->index);
	printf("    ");
	prt(road_index[42],"43",player->index);
	printf("\n");
    printf("      * ");
	prt(road_index[43],"44",player->index);
	printf("*       * ");
	prt(road_index[44],"45",player->index);
	printf("*       * ");
	prt(road_index[45],"46",player->index);
	printf("*\n");
    printf("     ");
	prt(road_index[46],"47",player->index);
	printf("    ");
	prt(road_index[47],"48",player->index);
	printf("    ");
	prt(road_index[48],"49",player->index);
	printf("    ");
	prt(road_index[49],"50",player->index);
	printf("    ");
	prt(road_index[50],"51",player->index);
	printf("    ");
	prt(road_index[51],"52",player->index);
	printf("\n");
    printf("    *       * ");
	prt(road_index[52],"53",player->index);
	printf("*       * ");
	prt(road_index[53],"54",player->index);
	printf("*       *\n");
    printf("     ");
	prt(road_index[54],"55",player->index);
	printf("    ");
	prt(road_index[55],"56",player->index);
	printf("    ");
	prt(road_index[65],"57",player->index);
	printf("    ");
	prt(road_index[57],"58",player->index);
	printf("    ");
	prt(road_index[58],"59",player->index);
	printf("    ");
	prt(road_index[59],"60",player->index);
	printf("\n");
    printf("      * ");
	prt(road_index[60],"61",player->index);
	printf("*       * ");
	prt(road_index[61],"62",player->index);
	printf("*       * ");
	prt(road_index[62],"63",player->index);
	printf("*\n");
    printf("           ");
	prt(road_index[63],"64",player->index);
	printf("    ");
	prt(road_index[64],"65",player->index);
	printf("    ");
	prt(road_index[65],"66",player->index);
	printf("    ");
	prt(road_index[66],"67",player->index);
	printf("\n");
    printf("            * ");
	prt(road_index[67],"68",player->index);
	printf("*       * ");
	prt(road_index[68],"69",player->index);
	printf("*\n");
    printf("                 ");
	prt(road_index[69],"70",player->index);
	printf("    ");
	prt(road_index[70],"71",player->index);printf("\n");
    printf("                  * ");
	prt(road_index[71],"72",player->index);
	printf("*\n\n");

    //printf("        Press any button to quit!\n");
    //refresh();

    // Wait for user input
    //getch();

    //endwin();
	//clear();
}


